#!/usr/bin/env python3
"""
Sprite generation pipeline for ADHD-Dev CLI tool.
Reads 20 PNG files from assets/crayfish/ and generates src/tui/crawfish-art.ts.
AUTO-GENERATED by scripts/generate-sprites.py — DO NOT EDIT the output file.
"""

import os
import sys
import json
import math
from pathlib import Path

try:
    from PIL import Image
    import numpy as np
except ImportError:
    print("ERROR: Missing dependencies. Run: pip3 install Pillow numpy")
    sys.exit(1)

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent
ASSETS_DIR = PROJECT_DIR / "assets" / "crayfish"
OUTPUT_FILE = PROJECT_DIR / "src" / "tui" / "crawfish-art.ts"

# ---------------------------------------------------------------------------
# Level definitions
# ---------------------------------------------------------------------------
LEVELS = [
    (1, "baby"),
    (2, "juvenile"),
    (3, "adult"),
    (4, "warrior"),
    (5, "king"),
]

STATES = ["idle", "working", "complete", "sleeping"]

NUM_FRAMES = 4

# Target widths for compact (halfblock) rendering — in characters
COMPACT_WIDTHS = {
    "baby": 30, "juvenile": 30,
    "adult": 40, "warrior": 40, "king": 40,
}

# Target widths for hires (ASCII density) rendering — in characters
HIRES_WIDTHS = {
    "baby": 80, "juvenile": 80,
    "adult": 100, "warrior": 100, "king": 100,
}

# ASCII density charset (12 levels, darkest to brightest)
DENSITY_CHARS = ' .·:;+x%#@█'


# ---------------------------------------------------------------------------
# Step 1: Load and normalize dimensions per level
# ---------------------------------------------------------------------------

def load_images():
    """Load all 20 PNGs and return dict: {level_name: {state: Image}}"""
    images = {}
    for _, level_name in LEVELS:
        images[level_name] = {}
        for state in STATES:
            fname = ASSETS_DIR / f"{level_name}_{state}.png"
            if not fname.exists():
                print(f"  WARNING: Missing {fname}")
                continue
            img = Image.open(fname).convert("RGBA")
            images[level_name][state] = img
    return images


def normalize_per_level(images):
    """
    For each level, compute max bounding box across all 4 state sprites.
    Center-pad each sprite to that max size with transparent pixels.
    Returns: {level_name: {state: Image (padded)}}
    """
    normalized = {}
    for _, level_name in LEVELS:
        level_imgs = images[level_name]
        max_w = max(img.width for img in level_imgs.values())
        max_h = max(img.height for img in level_imgs.values())
        padded = {}
        for state, img in level_imgs.items():
            new_img = Image.new("RGBA", (max_w, max_h), (0, 0, 0, 0))
            paste_x = (max_w - img.width) // 2
            paste_y = (max_h - img.height) // 2
            new_img.paste(img, (paste_x, paste_y))
            padded[state] = new_img
        normalized[level_name] = padded
    return normalized


# ---------------------------------------------------------------------------
# Step 2: Generate 4 animation frames per sprite
# ---------------------------------------------------------------------------

def shift_row(pixels, w, h, y, dx):
    """Shift row y horizontally by dx, filling with transparent pixels."""
    row = pixels[y, :, :].copy()
    new_row = np.zeros((w, 4), dtype=np.uint8)
    if dx > 0:
        new_row[dx:, :] = row[:w - dx, :]
    elif dx < 0:
        new_row[:w + dx, :] = row[-dx:, :]
    else:
        new_row = row
    pixels[y, :, :] = new_row


def animate_idle(base_pixels, w, h, phase):
    """Antenna/claw sway — top pixels sway more."""
    pixels = base_pixels.copy()
    for y in range(h):
        weight = max(0.0, 1.0 - y / h)
        dx = int(math.sin(phase + y * 0.15) * 2 * weight)
        if dx != 0:
            shift_row(pixels, w, h, y, dx)
    return pixels


def animate_working(base_pixels, w, h, phase):
    """Bounce + wave."""
    pixels = base_pixels.copy()
    bounce_dy = int(math.sin(phase) * 2)
    result = np.zeros_like(pixels)
    for y in range(h):
        amp = 1.5 + math.sin(y * 0.2) * 0.5
        dx = int(math.sin(phase + y * 0.25) * amp)
        sy = y - bounce_dy
        if 0 <= sy < h:
            src_row = pixels[sy, :, :].copy()
        else:
            src_row = np.zeros((w, 4), dtype=np.uint8)
        # shift by dx
        shifted = np.zeros((w, 4), dtype=np.uint8)
        if dx > 0:
            shifted[dx:, :] = src_row[:w - dx, :]
        elif dx < 0:
            shifted[:w + dx, :] = src_row[-dx:, :]
        else:
            shifted = src_row
        result[y, :, :] = shifted
    return result


def animate_complete(base_pixels, w, h, phase):
    """Pulse scale ±4%."""
    scale = 1.0 + math.sin(phase) * 0.04
    cy = h / 2.0
    cx = w / 2.0
    result = np.zeros_like(base_pixels)
    for y in range(h):
        for x in range(w):
            sy = int(cy + (y - cy) / scale)
            sx = int(cx + (x - cx) / scale)
            if 0 <= sy < h and 0 <= sx < w:
                result[y, x, :] = base_pixels[sy, sx, :]
    return result


def animate_sleeping(base_pixels, w, h, phase):
    """Breath effect ±3%."""
    breath = 1.0 + math.sin(phase) * 0.03
    result = np.zeros_like(base_pixels)
    for y in range(h):
        sy = int(h - (h - y) * breath)
        dx = int(math.sin(phase * 0.5 + y * 0.05) * 1)
        if 0 <= sy < h:
            src_row = base_pixels[sy, :, :].copy()
        else:
            src_row = np.zeros((w, 4), dtype=np.uint8)
        # shift by dx
        shifted = np.zeros((w, 4), dtype=np.uint8)
        if dx > 0:
            shifted[dx:, :] = src_row[:w - dx, :]
        elif dx < 0:
            shifted[:w + dx, :] = src_row[-dx:, :]
        else:
            shifted = src_row
        result[y, :, :] = shifted
    return result


ANIMATORS = {
    "idle": animate_idle,
    "working": animate_working,
    "complete": animate_complete,
    "sleeping": animate_sleeping,
}


def generate_frames(img, state):
    """Generate NUM_FRAMES animated pixel arrays for a given image and state."""
    w, h = img.size
    base_pixels = np.array(img)  # shape: (h, w, 4)
    frames = []
    for frame_idx in range(NUM_FRAMES):
        phase = (frame_idx / NUM_FRAMES) * 2 * math.pi
        animator = ANIMATORS[state]
        animated = animator(base_pixels, w, h, phase)
        frames.append(animated)
    return frames


# ---------------------------------------------------------------------------
# Step 3: Render COMPACT halfblock
# ---------------------------------------------------------------------------

def resize_for_compact(pixels_array, level_name, target_char_w):
    """
    Resize pixel array to target_char_w * 2 pixels wide (each char = 1 pixel wide,
    each char = 2 pixels tall). Height is auto-scaled, ensured even.
    Returns resized PIL Image.
    """
    h, w = pixels_array.shape[:2]
    target_px_w = target_char_w
    scale = target_px_w / w
    target_px_h = int(h * scale)
    if target_px_h % 2 != 0:
        target_px_h += 1

    img = Image.fromarray(pixels_array.astype(np.uint8), "RGBA")
    img = img.resize((target_px_w, target_px_h), Image.LANCZOS)
    return np.array(img)


def render_compact(pixels_array):
    """
    Render pixel array using halfblock characters.
    Each character = 2 vertical pixels.
    Returns list of strings (one per row of characters).
    """
    h, w = pixels_array.shape[:2]
    lines = []
    for y in range(0, h - 1, 2):
        line = ""
        for x in range(w):
            top = pixels_array[y, x]
            bot = pixels_array[y + 1, x]
            top_vis = top[3] >= 128
            bot_vis = bot[3] >= 128

            if top_vis and bot_vis:
                # Both visible: fg=top, bg=bottom, char=▀
                tr, tg, tb = int(top[0]), int(top[1]), int(top[2])
                br, bg, bb = int(bot[0]), int(bot[1]), int(bot[2])
                line += f"\x1b[38;2;{tr};{tg};{tb}m\x1b[48;2;{br};{bg};{bb}m\u2580\x1b[0m"
            elif top_vis:
                tr, tg, tb = int(top[0]), int(top[1]), int(top[2])
                line += f"\x1b[38;2;{tr};{tg};{tb}m\u2580\x1b[0m"
            elif bot_vis:
                br, bg, bb = int(bot[0]), int(bot[1]), int(bot[2])
                # Use ▄ for bottom-only — render as fg color with ▄
                line += f"\x1b[38;2;{br};{bg};{bb}m\u2584\x1b[0m"
            else:
                line += " "
        lines.append(line)
    return lines


# ---------------------------------------------------------------------------
# Step 4: Render HIRES ASCII density
# ---------------------------------------------------------------------------

def resize_for_hires(pixels_array, target_char_w):
    """
    Resize pixel array to target_char_w pixels wide.
    Height is auto-scaled (aspect ratio preserved, accounting for terminal char ratio).
    Returns resized pixel array.
    """
    h, w = pixels_array.shape[:2]
    target_px_w = target_char_w
    # Terminal chars are roughly 2:1 height:width, so compress height by 0.5
    scale = target_px_w / w
    target_px_h = max(1, int(h * scale * 0.5))

    img = Image.fromarray(pixels_array.astype(np.uint8), "RGBA")
    img = img.resize((target_px_w, target_px_h), Image.LANCZOS)
    return np.array(img)


def render_hires(pixels_array):
    """
    Render pixel array using ASCII density mapping.
    Returns list of strings (one per row).
    """
    h, w = pixels_array.shape[:2]
    n_chars = len(DENSITY_CHARS)
    lines = []
    for y in range(h):
        line = ""
        for x in range(w):
            px = pixels_array[y, x]
            alpha = int(px[3])
            if alpha < 128:
                line += " "
            else:
                r, g, b = int(px[0]), int(px[1]), int(px[2])
                lum = 0.299 * r + 0.587 * g + 0.114 * b
                idx = min(int(lum / 255.0 * (n_chars - 1)), n_chars - 1)
                char = DENSITY_CHARS[idx]
                line += f"\x1b[38;2;{r};{g};{b}m{char}\x1b[0m"
        lines.append(line)
    return lines


# ---------------------------------------------------------------------------
# Step 5: Generate TypeScript output
# ---------------------------------------------------------------------------

LEVEL_COMMENTS = {1: "Baby", 2: "Juvenile", 3: "Adult", 4: "Warrior", 5: "King"}


def frames_to_ts(frames_by_state):
    """
    Convert {state: [[line, ...], ...]} to TypeScript object literal string.
    Uses json.dumps for safe string escaping of each line.
    """
    parts = []
    for state in STATES:
        frame_list = frames_by_state[state]
        frame_strs = []
        for frame_lines in frame_list:
            # json.dumps each line for safe escaping
            encoded_lines = [json.dumps(line) for line in frame_lines]
            frame_str = "      [\n        " + ",\n        ".join(encoded_lines) + ",\n      ]"
            frame_strs.append(frame_str)
        state_str = f"    {state}: [\n" + ",\n".join(frame_strs) + "\n    ]"
        parts.append(state_str)
    return "  {\n" + ",\n".join(parts) + "\n  }"


def generate_typescript(compact_data, hires_data):
    """
    Generate the full TypeScript file content.
    compact_data: {level_num: {state: [[lines], ...]}}
    hires_data: same structure
    """
    lines = []
    lines.append("// AUTO-GENERATED by scripts/generate-sprites.py — DO NOT EDIT")
    lines.append("// 5 levels × 4 states × 4 frames × 2 resolutions")
    lines.append("")
    lines.append("type FrameLines = string[];")
    lines.append("type FrameMap = Record<string, FrameLines[]>;")
    lines.append("")

    # COMPACT export
    lines.append("export const COMPACT: Record<number, FrameMap> = {")
    for level_num, level_name in LEVELS:
        comment = LEVEL_COMMENTS[level_num]
        lines.append(f"  {level_num}: {{  // {comment}")
        for state in STATES:
            frame_list = compact_data[level_num][state]
            frame_strs = []
            for frame_lines in frame_list:
                encoded = [json.dumps(l) for l in frame_lines]
                inner = ",\n        ".join(encoded)
                frame_strs.append(f"      [\n        {inner},\n      ]")
            frames_joined = ",\n".join(frame_strs)
            lines.append(f"    {state}: [")
            lines.append(frames_joined)
            lines.append("    ],")
        lines.append("  },")
    lines.append("};")
    lines.append("")

    # HIRES export
    lines.append("export const HIRES: Record<number, FrameMap> = {")
    for level_num, level_name in LEVELS:
        comment = LEVEL_COMMENTS[level_num]
        lines.append(f"  {level_num}: {{  // {comment}")
        for state in STATES:
            frame_list = hires_data[level_num][state]
            frame_strs = []
            for frame_lines in frame_list:
                encoded = [json.dumps(l) for l in frame_lines]
                inner = ",\n        ".join(encoded)
                frame_strs.append(f"      [\n        {inner},\n      ]")
            frames_joined = ",\n".join(frame_strs)
            lines.append(f"    {state}: [")
            lines.append(frames_joined)
            lines.append("    ],")
        lines.append("  },")
    lines.append("};")
    lines.append("")

    # getCrawfishArt function
    lines.append(
        "export function getCrawfishArt(level: number, state: string, frame: number): string[] {"
    )
    lines.append("  const lvl = COMPACT[level];")
    lines.append("  if (!lvl) return [];")
    lines.append("  const stateFrames = lvl[state];")
    lines.append("  if (!stateFrames) return [];")
    lines.append("  return stateFrames[frame % stateFrames.length] ?? [];")
    lines.append("}")
    lines.append("")

    # getCrawfishHires function
    lines.append(
        "export function getCrawfishHires(level: number, state: string, frame: number): string[] {"
    )
    lines.append("  const lvl = HIRES[level];")
    lines.append("  if (!lvl) return [];")
    lines.append("  const stateFrames = lvl[state];")
    lines.append("  if (!stateFrames) return [];")
    lines.append("  return stateFrames[frame % stateFrames.length] ?? [];")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main pipeline
# ---------------------------------------------------------------------------

def main():
    print("=== Crawfish Sprite Generation Pipeline ===")
    print(f"Assets dir: {ASSETS_DIR}")
    print(f"Output:     {OUTPUT_FILE}")
    print()

    # Verify assets exist
    if not ASSETS_DIR.exists():
        print(f"ERROR: Assets directory not found: {ASSETS_DIR}")
        sys.exit(1)

    # Load images
    print("Loading images...")
    images = load_images()

    # Normalize dimensions per level
    print("Normalizing dimensions per level...")
    normalized = normalize_per_level(images)
    for _, level_name in LEVELS:
        sample = next(iter(normalized[level_name].values()))
        print(f"  {level_name}: normalized to {sample.width}x{sample.height}")

    # Generate all frames + render
    compact_data = {}  # {level_num: {state: [frame_lines, ...]}}
    hires_data = {}

    for level_num, level_name in LEVELS:
        compact_data[level_num] = {}
        hires_data[level_num] = {}
        compact_w = COMPACT_WIDTHS[level_name]
        hires_w = HIRES_WIDTHS[level_name]

        for state in STATES:
            img = normalized[level_name][state]
            compact_frames = []
            hires_frames = []

            for frame_idx in range(NUM_FRAMES):
                print(f"  Processing {level_name}_{state} frame {frame_idx}...")
                phase = (frame_idx / NUM_FRAMES) * 2 * math.pi

                # Generate animated pixels
                w, h = img.size
                base_pixels = np.array(img)
                animator = ANIMATORS[state]
                animated = animator(base_pixels, w, h, phase)

                # Compact render
                compact_pixels = resize_for_compact(animated, level_name, compact_w)
                compact_lines = render_compact(compact_pixels)
                compact_frames.append(compact_lines)

                # Hires render
                hires_pixels = resize_for_hires(animated, hires_w)
                hires_lines = render_hires(hires_pixels)
                hires_frames.append(hires_lines)

            compact_data[level_num][state] = compact_frames
            hires_data[level_num][state] = hires_frames

    # Generate TypeScript
    print("\nGenerating TypeScript file...")
    ts_content = generate_typescript(compact_data, hires_data)

    # Ensure output directory exists
    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(ts_content)

    file_size = OUTPUT_FILE.stat().st_size
    line_count = ts_content.count("\n")
    print(f"\nOutput written: {OUTPUT_FILE}")
    print(f"  Lines: {line_count:,}")
    print(f"  Size:  {file_size / 1024:.1f} KB")
    print("\nDone!")


if __name__ == "__main__":
    main()
